meta_product_name: "Just $10"
meta_title: "Just $10 - Best app for decluttering or treasure hunt"
meta_description: "Do you have stuff in your house doing nothing but you don't have time to put it on Gumtree? or Are you looking for bargain in your neighbourhood? We have great app for you."
meta_image: "cover.png" # should exist in `app/assets/images/`
